### ISSUE TITLE
Add description for how it works

### ISSUE THREAD

**Issue by php-coder** [justice3120/danger-conflict_checker#4]
Please, add a description for how it works.

> Warn about the conflict between PRs.

It's not clear how it finds these PRs and how many PRs will be scanned. Does it scan for all the PRs in a repository?

**Comment by justice3120** [comment]
Hi, @php-coder 
This checks all Pull Requests that have the same destination as working Pull Request.
I will update README after.

**Comment by justice3120** [comment]
Hi, @php-coder,
I update the description. 
And added a link to example repository that shows how this plugin works.

**Comment by php-coder** [comment]
Thanks!
